In [1]:
import numpy as np
import gym
import random
from IPython.display import clear_output

In [4]:
env=gym.make("FrozenLake-v1")

In [5]:
action_size=env.action_space.n
state_size=env.observation_space.n

In [6]:
q_table=np.zeros((state_size,action_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [26]:
num_episodes=10000
max_steps_per_episode=100

learning_rate=0.1
discount_rate=0.99

exploration_rate=1
max_exploration_rate=1
min_exploration_rate=0.01
#exploration_decay_rate=0.01
exploration_decay_rate=0.001

In [29]:
rewards=[]

# Q-Learning

for episodes in range(num_episodes):
    state = env.reset()
    done = False
    rewards_curr = 0
    
    for step in range(max_steps_per_episode):
        exploration_rate_threshold = random.uniform(0,1)
        
        if exploration_rate_threshold>exploration_rate:
            action = np.argmax(q_table[state,:])#check this state syntax
            
            
        else:
            action = env.action_space.sample()
            
        new_state,reward, done, info = env.step(action)
        
        q_table[state,action]=q_table[state,action]*(1-learning_rate)+\
        learning_rate*(reward+discount_rate*np.max(q_table[new_state,:]))
        
        state=new_state
        rewards_curr+=reward
        
        if done==True:
            break
            
    exploration_rate=min_exploration_rate+(max_exploration_rate-min_exploration_rate)*np.exp(-exploration_decay_rate*episodes)
        
    rewards.append(rewards_curr)
        
rewards_per1000=np.split(np.array(rewards),num_episodes/1000)
count = 1000

for i in rewards_per1000 :
    print(count ," : ",str(sum(i/1000)))
    count+=1000
            

        

1000  :  0.05400000000000004
2000  :  0.20500000000000015
3000  :  0.4140000000000003
4000  :  0.5560000000000004
5000  :  0.6300000000000004
6000  :  0.6490000000000005
7000  :  0.6740000000000005
8000  :  0.6970000000000005
9000  :  0.6740000000000005
10000  :  0.6620000000000005
